AWSTemplateFormatVersion: '2010-09-09'
Description: Sample SAM Template for NotoriousRBD
Globals:
  Function:
    Timeout: 10
Outputs:
  NotoriousRBDApi:
    Description: API Gateway endpoint URL for Prod stage for Debugging Example function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/DebuggingExample/
  NotoriousRBDFunction:
    Description: Debugging Example Lambda Function ARN
    Value:
      Fn::GetAtt:
      - NotoriousRBDFunction
      - Arn
  NotoriousRBDFunctionIamRole:
    Description: Implicit IAM Role created for Debugging Example function
    Value:
      Fn::GetAtt:
      - NotoriousRBDFunctionRole
      - Arn
Resources:
  NotoriousRBDFunction:
    Properties:
      CodeUri: s3://notorious-rbd-deploy/6cdc0a36f517c9e313c5344b0a9dc7b6
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Genres:
          Properties:
            Method: get
            Path: /genres
          Type: Api
        SearchGames:
          Properties:
            Method: get
            Path: /games
          Type: Api
      FunctionName: NotoriousRBD
      Handler: NotoriousRBD::NotoriousRBD.Functions::Get
      Runtime: dotnetcore2.1
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
